#!/usr/bin/python3

import subprocess, tempfile, os
import numpy as np

defaults = {
    "diameter": 25 / 1000,
    "losses": 0,
    "loading": 0,
    "segments": 21,
    "vf": .66,
    "power": 100,
    "feed": 50
}


def run_process(text):
    name = tempfile.mktemp()
    command = 'nec2c -i %s -o /dev/stdout' % name
    with open(name, "wb") as f:
        f.write(text.encode()) 
    proc = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE)
    result = proc.stdout.read().decode()
    proc.wait()
    os.unlink(name)
    return result


def run_nec(text):
    tag = None
    im = []
    buf = run_process(text)
    f = iter(buf.splitlines())
    for line in f:
        data = line.split()
        if len(data) == 10 and data[0].isdigit() and '.' in line: break
    while True:
        data = line.split() 
        if not len(data): break
        x = np.complex(np.double(data[6]), np.double(data[7]))
        if tag != data[1]:
            im.append(x)
            tag = data[1]
        line = next(f)
    return im


def generate_input(data, voltages):
    frequency = data["frequency"]
    elements = data['elements']
    height = data['height']
    radius = data["diameter"] / 2
    losses = data["losses"]
    loading = data["loading"]
    segments = data["segments"]
    text = ""
    n = len(elements)
    for i in range(n):
        tag = i + 1
        fmt = "GW {tag} {segments} {x:g} {y:g} 0 {x:g} {y:g} {height} {radius}\n"
        text += fmt.format(tag=tag, segments=segments, 
                           x=elements[i][0], y=elements[i][1], 
                           height=height, radius=radius)
    text += "GE 1\n"  # ground plane is present
    text += "GN 1\n"  # perfect ground
    text += "FR 0 0 0 0 {:f}\n".format(frequency)
    for i in range(n):
        tag = i + 1
        text += "LD 4 {:d} 1 1 {:f} {:f}\n".format(tag, losses, loading)
    for i in range(n):
        tag = i + 1
        text += "EX 0 {:d} 1 0 {:g} {:g}\n".format(tag, voltages[i].real, voltages[i].imag)
    text += "XQ\n"
    text += "EN\n"
    return text


def multiply(zij, ii):
    ei = np.matrix(zij) * np.matrix(ii).T
    return np.array(ei).T[0]


def autoload(data):
    d = { "elements": [ (0, 0) ] }
    ei = [ 1 ]
    ii = run_nec(generate_input(dict(data, **d), ei))
    zself = 1 / ii[0]
    print('! autoload vertical base   = {:.4f}j'.format(-zself.imag))
    data["loading"] = -zself.imag


def mutual(data):
    n = len(data["elements"])
    zij = np.zeros((n, n), dtype=np.complex)
    for k in range(n):
        ei = np.ones(n) * 1e-20
        ei[k] = 1
        ii = run_nec(generate_input(data, ei))
        zij[:,k] = ii
    zij = np.array(np.linalg.inv(np.matrix(zij)))
    return zij


def error_norm(zij, data):
    n = zij.shape[0]
    ii = np.ones(n)
    ei = multiply(zij, ii)
    err = ii - run_nec(generate_input(data, ei))
    print('! error norm       = {:g}'.format(np.linalg.norm(err)))


def to_complex(buf, f=None, vf=None):
    buf = buf.strip()
    if '/' in buf:
        r, theta = buf.split('/')
        if theta[-2:] == 'ft':
            theta = np.double(theta[:-2]) * .3048
            theta = 360 * theta / vf / (300 / f)
        elif theta[-1:] == 'm':
            theta = np.double(theta[:-1])
            theta = 360 * theta / vf / (300 / f)
        return np.double(r) * np.exp(1j * np.deg2rad(np.double(theta)))
    else:
        return np.complex(buf)


def to_distance(buf):
    buf = buf.strip()
    if len(buf) > 2:
        suffix = buf[-2:]
        s = buf[:-2]
        if suffix == 'cm':
            return np.double(s) * .01
        if suffix == 'mm':
            return np.double(s) * .001
        if suffix == 'in':
            return np.double(s) * .0254
        if suffix == 'ft':
            return np.double(s) * .3048
    return np.double(buf)
    

def parallel(*zi):
    return 1 / np.sum([ 1 / x for x in zi ])


def tline(deg, zo=50):
    theta = np.deg2rad(deg)
    return np.matrix([
        [ np.cos(theta), 1j * zo * np.sin(theta) ],
        [ 1j * np.sin(theta) / zo, np.cos(theta) ]
    ])


def print_drive(zij, data):
    n = zij.shape[0]
    frequency = data["frequency"]
    ii = np.array(data["currents"])
    ei = multiply(zij, ii)
    # handle tlines
    for i, x in enumerate(data["tlines"]):
        x = to_complex(x, f=frequency, vf=data["vf"])
        ei[i], ii[i] = multiply(tline(np.rad2deg(np.angle(x)), zo=np.abs(x)), [ei[i], ii[i]])
    if data.get("k2bt"): 
        return solve(ei, ii, data)
    elif data.get("divider"): 
        return solve(ei, ii, data, divider=True)
    else:
        zi = ei / ii
        ztot = parallel(zi)
        print('{:<8g}'.format(frequency), end="")
        print(','.join([ ' {:8.4f} {:+8.4f}j'.format(x.real, x.imag) for x in zi ]))
        print('! E in MA notation =', end="")
        print(','.join([ ' {:8.4f} {:8.4f}'.format(np.abs(x), np.rad2deg(np.angle(x))) for x in ei ]))
        print('! I in MA notation =', end="")
        print(','.join([ ' {:8.4f} {:8.4f}'.format(np.abs(x), np.rad2deg(np.angle(x))) for x in ii ]))
        print('! Z in parallel    =', end="")
        print(' {:8.4f} {:+8.4f}j'.format(ztot.real, ztot.imag))


def print_mutual(zij, data):
    n = zij.shape[0]
    frequency = data["frequency"]
    print('{:<8g}'.format(frequency), end="")
    for i in range(n):
        if i > 0: print('{:<8s}'.format(''), end="")
        print(','.join([ ' {:8.4f} {:+8.4f}j'.format(
              zij[i][j].real, zij[i][j].imag) for j in range(n) ]))

   
def main(*args):
    args = list(args)
    kw = { "elements": [], "tlines": [] }
    while args:
        opt = args.pop(0)
        if opt == '-debug':
            kw["debug"] = True
        elif opt == '-halfwave':
            kw["halfwave"] = True
        elif opt == '-autoload':
            kw["autoload"] = True
        elif opt == '-k2bt':
            kw["k2bt"] = True
        elif opt == '-divider':
            kw["divider"] = True
        elif opt == '-freq':
            kw["frequencies"] = [ np.double(x) for x in args.pop(0).split(',') ]
        elif opt == '-loss':
            kw["losses"] = np.double(args.pop(0))
        elif opt == '-load':
            kw["loading"] = np.double(args.pop(0))
        elif opt == '-segs':
            kw["segments"] = np.int(args.pop(0))
        elif opt == '-height':
            kw["height"] = to_distance(args.pop(0))
        elif opt == '-diam':
            kw["diameter"] = to_distance(args.pop(0))
        elif opt == '-el':
            kw["elements"].append([ to_distance(x) for x in args.pop(0).split(',') ])
        elif opt == '-currents':
            kw["currents"] = [ to_complex(x) for x in args.pop(0).split(',') ]
        elif opt == '-tie':
            kw["tie"] = [ np.int(x) for x in args.pop(0).split(',') ]
        elif opt == '-tlines':
            kw["tlines"] = args.pop(0).split(',')
        elif opt == '-vf':
            kw["vf"] = np.double(args.pop(0))
        elif opt == '-power':
            kw["power"] = np.double(args.pop(0))
        elif opt == '-feed':
            kw["feed"] = np.double(args.pop(0))
        else:
            raise ValueError

    kw = dict(defaults, **kw)
    print("! MHZ Z RI R 1")
    for freq in kw["frequencies"]:
        kw["frequency"] = freq

        if kw.get('autoload'):
            autoload(kw)
        zij = mutual(kw)

        # calculate error norm
        if kw.get('debug'):
            error_norm(zij, kw)

        # display results
        if kw.get("currents"):
            print_drive(zij, kw)
        else:
            print_mutual(zij, kw)


######################


def lmatch(ZS, ZL):
    """
    ZS <---+---X2--< ZL
           X1   
    """
    RS, XS = ZS.real, ZS.imag
    RL, XL = ZL.real, ZL.imag
    QS = RS / RL - 1 + XS**2 / (RS * RL)
    Q = np.sqrt(QS)
    X1 = (XS + np.array([1, -1]) * Q * RS) / (RS / RL - 1)
    X2 = -(XL + np.array([1, -1]) * Q * RL)
    return np.array([X1, X2]).T


def component(x, f, precision=5):
    if np.isinf(x) or np.isnan(x) or x == 0: return '-'
    f = f * 1e6
    w = 2 * np.pi * f
    x = 1 / (w * x) if x < 0 else x / w
    UNITS = 'FH'
    SUFFIX = ["f", "p", "n", "u", "m", "", "k", "M", "G"]
    exp = np.floor(np.log10(np.absolute(x)))
    mant = np.round(x / 10**exp, precision-1)
    p = np.int(exp // 3)
    value = (mant * 10**exp) / 10**(3 * p)
    return "%6.4g%s%s" % (np.absolute(value), SUFFIX[p-4], UNITS[0 if x < 0 else 1])


def pishift(theta, zo):
    theta = np.deg2rad(theta)
    xs = zo.real * np.sin(theta)
    xp = -zo.real * np.sin(theta) / (1 - np.cos(theta))
    return xs, xp


def teeshift(theta, zo):
    theta = np.deg2rad(theta)
    xs = zo.real * (1 - np.cos(theta)) / np.sin(theta)
    xp = -zo.real / np.sin(theta)
    return xs, xp


def pinet(v, xs, xp):
    v = multiply([[1, 0], [1 / (1j*xp), 1]], v)  # shunt
    v = multiply([[1, 1j*xs], [0, 1]], v)        # series
    v = multiply([[1, 0], [1 / (1j*xp), 1]], v)  # shunt
    return v

def teenet(v, xs, xp):
    v = multiply([[1, 1j*xs], [0, 1]], v)        # series
    v = multiply([[1, 0], [1 / (1j*xp), 1]], v)  # shunt
    v = multiply([[1, 1j*xs], [0, 1]], v)        # series
    return v


def solve(ei, ii, data, divider=False):
    n = len(ei)
    freq = data["frequency"]
    zi = ei / ii

    power = np.abs(ii**2) * zi.real
    ratio = np.sqrt(data["power"] / np.sum(power))
    ei *= ratio
    ii *= ratio

    if data.get("tie"):
        isum = np.sum([ ii[i-1] for i in data["tie"] ])
        for i in data["tie"]: ii[i-1] = isum
        zi = ei / ii

    power = np.abs(ii**2) * zi.real
    feede = np.sqrt(data["power"] * data["feed"])
    if divider:
        feedr = [ data["feed"] ] * n 
    else:
        feedr = [ feede**2 / w for w in power ]
    match = [ np.concatenate([ lmatch(zi[i], feedr[i]), lmatch(feedr[i], zi[i]) ]) for i in range(n) ]
    combo = np.array([ [ i // (4 ** (n - k - 1)) % 4 for k in range(n) ] for i in range(4 ** n) ])

    print("! MHZ  LINE               ZA       X1         X2          ZTUNE         ELINE        DPHASE", end="")
    if data.get("halfwave"): 
        print('       HALFWAVE        DPHASE', end="")
    print("  SHUNTPI SERIESPI  SERIESTEE SHUNTTEE")

    for d in combo:
        net = np.array([ match[i][k] for i, k in enumerate(d) ])
        if np.any(np.isnan(net.flatten())): continue

        print('!')
        for ref in range(n):

            # tune all tower lines for phase shifting

            line = np.array([ ei, ii ]).T
            for i, m, reverse in zip(range(n), net, d > 1):
                if reverse:
                    line[i] = multiply([[1, 1j*m[1]], [0, 1]], line[i])        # series
                    line[i] = multiply([[1, 0], [1 / (1j*m[0]), 1]], line[i])  # shunt
                else:
                    line[i] = multiply([[1, 0], [1 / (1j*m[0]), 1]], line[i])  # shunt
                    line[i] = multiply([[1, 1j*m[1]], [0, 1]], line[i])        # series

            for hw in (range(1, 5) if data.get("halfwave") else range(1)):          
                for i, m, reverse in zip(range(n), net, d > 1):
                    print('{:<8g} {:2d} {:16.5g}'.format(freq, i + 1, zi[i]), end=" ")
                    if reverse:
                        print('{:>8s} / {:>8s}'.format(component(m[1], freq), component(m[0], freq)), end=" ")
                    else:
                        print('{:>8s} \\ {:>8s}'.format(component(m[0], freq), component(m[1], freq)), end=" ")

                    zo = line[i][0] / line[i][1]
                    print('{:14.2f}'.format(zo), end=" ")
                    print('{:9.4f} {:8.3f}'.format(np.abs(line[i][0]), np.rad2deg(np.angle(line[i][0]))), end=" ")

                    v = line[i]
                    theta = np.rad2deg(np.angle(line[ref][0]) - np.angle(v[0]))
                    theta = np.mod(theta + 180, 360) - 180
                    print('{:8.3f}'.format(theta), end=" ")

                    ######################################

                    if hw > 0:
                        if i == ref:
                            print('{:>8s} {:>8s}  '.format('-', '-'), end=" ")
                        elif hw == 1:
                            xs, xp = pishift(-90, zo.real)
                            print('{:>8s} {:>8s} P'.format(component(xp, freq), component(xs, freq)), end=" ")
                            v = pinet(v, xs, xp)
                        elif hw == 2:
                            xs, xp = pishift(90, zo.real)
                            print('{:>8s} {:>8s} P'.format(component(xp, freq), component(xs, freq)), end=" ")
                            v = pinet(v, xs, xp)
                        elif hw == 3:
                            xs, xp = teeshift(-90, zo.real)
                            print('{:>8s} {:>8s} T'.format(component(xs, freq), component(xp, freq)), end=" ")
                            v = teenet(v, xs, xp)
                        elif hw == 4:
                            xs, xp = teeshift(90, zo.real)
                            print('{:>8s} {:>8s} T'.format(component(xs, freq), component(xp, freq)), end=" ")
                            v = teenet(v, xs, xp)
                        else:
                            raise ValueError

                        theta = np.rad2deg(np.angle(line[ref][0]) - np.angle(v[0]))
                        theta = np.mod(theta + 180, 360) - 180
                        print('{:8.3f}'.format(theta), end=" ")

                    ######################################

                    memory = v
                    xs, xp = pishift(theta, zo.real)
                    print('{:>8s} {:>8s}'.format(component(xp, freq), component(xs, freq)), end=" ")
                    if i != ref: v = pinet(v, xs, xp)
                    if data.get("debug"): print('%.4f' % np.abs(np.angle(v[0]) - np.angle(line[ref][0])), end=" ")
                    if data.get("debug"): print('%.4f' % (np.abs(v[1])**2 * (v[0]/v[1]).real), end=" ")

                    v = memory
                    xs, xp = teeshift(theta, zo.real)
                    print('| {:>8s} {:>8s}'.format(component(xs, freq), component(xp, freq)), end=" ")
                    if i != ref: v = teenet(v, xs, xp)
                    if data.get("debug"): print('%.4f' % np.abs(np.angle(v[0]) - np.angle(line[ref][0])), end=" ")
                    if data.get("debug"): print('%.4f' % (np.abs(v[1])**2 * (v[0]/v[1]).real), end=" ")
                    print()


if __name__ == "__main__":
    import sys
    np.seterr(divide='ignore', invalid='ignore')
    main(*sys.argv[1:])


