#!/usr/bin/python3

import subprocess, tempfile, os
import numpy as np

defaults = {
    "diameter": 25 / 1000,
    "losses": 0,
    "loading": 0,
    "segments": 21,
    "vf": .66,
    "power": 100,
    "feed": 50
}


def run_process(text):
    name = tempfile.mktemp()
    command = 'nec2c -i %s -o /dev/stdout' % name
    with open(name, "wb") as f:
        f.write(text.encode()) 
    proc = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE)
    result = proc.stdout.read().decode()
    proc.wait()
    os.unlink(name)
    return result


def run_nec(text):
    tag = None
    im = []
    buf = run_process(text)
    f = iter(buf.splitlines())
    for line in f:
        data = line.split()
        if len(data) == 10 and data[0].isdigit() and '.' in line: break
    while True:
        data = line.split() 
        if not len(data): break
        x = np.complex(np.double(data[6]), np.double(data[7]))
        if tag != data[1]:
            im.append(x)
            tag = data[1]
        line = next(f)
    return im


def generate_input(data, voltages):
    frequency = data["frequency"]
    elements = data['elements']
    height = data['height']
    radius = data["diameter"] / 2
    losses = data["losses"]
    loading = data["loading"]
    segments = data["segments"]
    text = ""
    n = len(elements)
    for i in range(n):
        tag = i + 1
        fmt = "GW {tag} {segments} {x:g} {y:g} 0 {x:g} {y:g} {height} {radius}\n"
        text += fmt.format(tag=tag, segments=segments, 
                           x=elements[i][0], y=elements[i][1], 
                           height=height, radius=radius)
    text += "GE 1\n"  # ground plane is present
    text += "GN 1\n"  # perfect ground
    text += "FR 0 0 0 0 {:f}\n".format(frequency)
    for i in range(n):
        tag = i + 1
        text += "LD 4 {:d} 1 1 {:f} {:f}\n".format(tag, losses, loading)
    for i in range(n):
        tag = i + 1
        text += "EX 0 {:d} 1 0 {:g} {:g}\n".format(tag, voltages[i].real, voltages[i].imag)
    text += "XQ\n"
    text += "EN\n"
    return text


def multiply(zij, ii):
    ei = np.matrix(zij) * np.matrix(ii).T
    return np.array(ei).T[0]


def autoload(data):
    d = { "elements": [ (0, 0) ] }
    ei = [ 1 ]
    ii = run_nec(generate_input(dict(data, **d), ei))
    zself = 1 / ii[0]
    print('! autoload vertical base   = {:.4f}j'.format(-zself.imag))
    data["loading"] = -zself.imag


def mutual(data):
    n = len(data["elements"])
    zij = np.zeros((n, n), dtype=np.complex)
    for k in range(n):
        ei = np.ones(n) * 1e-20
        ei[k] = 1
        ii = run_nec(generate_input(data, ei))
        zij[:,k] = ii
    zij = np.array(np.linalg.inv(np.matrix(zij)))
    return zij


def error_norm(zij, data):
    n = zij.shape[0]
    ii = np.ones(n)
    ei = multiply(zij, ii)
    err = ii - run_nec(generate_input(data, ei))
    print('! error norm       = {:g}'.format(np.linalg.norm(err)))


def to_complex(buf, f=None, vf=None):
    buf = buf.strip()
    if '/' in buf:
        r, theta = buf.split('/')
        if theta[-2:] == 'ft':
            theta = np.double(theta[:-2]) * .3048
            theta = 360 * theta / vf / (300 / f)
        elif theta[-1:] == 'm':
            theta = np.double(theta[:-1])
            theta = 360 * theta / vf / (300 / f)
        return np.double(r) * np.exp(1j * np.deg2rad(np.double(theta)))
    else:
        return np.complex(buf)


def to_distance(buf):
    buf = buf.strip()
    if len(buf) > 2:
        suffix = buf[-2:]
        s = buf[:-2]
        if suffix == 'cm':
            return np.double(s) * .01
        if suffix == 'mm':
            return np.double(s) * .001
        if suffix == 'in':
            return np.double(s) * .0254
        if suffix == 'ft':
            return np.double(s) * .3048
    return np.double(buf)
    

def parallel(*zi):
    return 1 / np.sum([ 1 / x for x in zi ])


def tline(deg, zo=50):
    theta = np.deg2rad(deg)
    return np.matrix([
        [ np.cos(theta), 1j * zo * np.sin(theta) ],
        [ 1j * np.sin(theta) / zo, np.cos(theta) ]
    ])


def print_drive(zij, data):
    n = zij.shape[0]
    frequency = data["frequency"]
    ii = np.array(data["currents"])
    ei = multiply(zij, ii)
    # handle tlines
    for i, x in enumerate(data["tlines"]):
        x = to_complex(x, f=frequency, vf=data["vf"])
        ei[i], ii[i] = multiply(tline(np.rad2deg(np.angle(x)), zo=np.abs(x)), [ei[i], ii[i]])
    if data.get("k2bt") or data.get("divider1") or data.get("divider2") or data.get("divider3"): 
        return solve(ei, ii, data)
    else:
        zi = ei / ii
        ztot = parallel(zi)
        print('{:<8g}'.format(frequency), end="")
        print(','.join([ ' {:8.4f} {:+8.4f}j'.format(x.real, x.imag) for x in zi ]))
        print('! E in MA notation =', end="")
        print(','.join([ ' {:8.4f} {:8.4f}'.format(np.abs(x), np.rad2deg(np.angle(x))) for x in ei ]))
        print('! I in MA notation =', end="")
        print(','.join([ ' {:8.4f} {:8.4f}'.format(np.abs(x), np.rad2deg(np.angle(x))) for x in ii ]))
        print('! Z in parallel    =', end="")
        print(' {:8.4f} {:+8.4f}j'.format(ztot.real, ztot.imag))


def print_mutual(zij, data):
    n = zij.shape[0]
    frequency = data["frequency"]
    print('{:<8g}'.format(frequency), end="")
    for i in range(n):
        if i > 0: print('{:<8s}'.format(''), end="")
        print(','.join([ ' {:8.4f} {:+8.4f}j'.format(
              zij[i][j].real, zij[i][j].imag) for j in range(n) ]))

   
def main(*args):
    args = list(args)
    kw = { "elements": [], "tlines": [] }
    while args:
        opt = args.pop(0)
        if opt == '-debug':
            kw["debug"] = True
        elif opt == '-autoload':
            kw["autoload"] = True
        elif opt == '-k2bt':
            kw["k2bt"] = True
        elif opt == '-divider1':
            kw["divider1"] = True
        elif opt == '-divider2':
            kw["divider2"] = True
        elif opt == '-divider3':
            kw["divider3"] = True
        elif opt == '-freq':
            kw["frequencies"] = [ np.double(x) for x in args.pop(0).split(',') ]
        elif opt == '-loss':
            kw["losses"] = np.double(args.pop(0))
        elif opt == '-load':
            kw["loading"] = np.double(args.pop(0))
        elif opt == '-segs':
            kw["segments"] = np.int(args.pop(0))
        elif opt == '-height':
            kw["height"] = to_distance(args.pop(0))
        elif opt == '-diam':
            kw["diameter"] = to_distance(args.pop(0))
        elif opt == '-el':
            kw["elements"].append([ to_distance(x) for x in args.pop(0).split(',') ])
        elif opt == '-currents':
            kw["currents"] = [ to_complex(x) for x in args.pop(0).split(',') ]
        elif opt == '-tie':
            kw["tie"] = [ np.int(x) for x in args.pop(0).split(',') ]
        elif opt == '-tlines':
            kw["tlines"] = args.pop(0).split(',')
        elif opt == '-vf':
            kw["vf"] = np.double(args.pop(0))
        elif opt == '-power':
            kw["power"] = np.double(args.pop(0))
        elif opt == '-feed':
            kw["feed"] = np.double(args.pop(0))
        else:
            raise ValueError

    kw = dict(defaults, **kw)
    print("! MHZ Z RI R 1")
    for freq in kw["frequencies"]:
        kw["frequency"] = freq

        if kw.get('autoload'):
            autoload(kw)
        zij = mutual(kw)

        # calculate error norm
        if kw.get('debug'):
            error_norm(zij, kw)

        # display results
        if kw.get("currents"):
            print_drive(zij, kw)
        else:
            print_mutual(zij, kw)


######################


def lmatch(ZS, ZL):
    """
    ZS <---+---X2--< ZL
           X1   
    """
    RS, XS = ZS.real, ZS.imag
    RL, XL = ZL.real, ZL.imag
    QS = RS / RL - 1 + XS**2 / (RS * RL)
    Q = np.sqrt(QS)
    X1 = (XS + np.array([1, -1]) * Q * RS) / (RS / RL - 1)
    X2 = -(XL + np.array([1, -1]) * Q * RL)
    return np.array([X1, X2]).T


def component(x, f, precision=5):
    if np.isinf(x) or np.isnan(x) or x == 0: return '-'
    f = f * 1e6
    w = 2 * np.pi * f
    x = 1 / (w * x) if x < 0 else x / w
    UNITS = 'FH'
    SUFFIX = ["f", "p", "n", "u", "m", "", "k", "M", "G"]
    exp = np.floor(np.log10(np.absolute(x)))
    mant = np.round(x / 10**exp, precision-1)
    p = np.int(exp // 3)
    value = (mant * 10**exp) / 10**(3 * p)
    if p - 4 >= 0 or p - 4 < -len(SUFFIX):
        return "%7.2g%s" % (np.absolute(x), UNITS[0 if x < 0 else 1])
    else:
        return "%6.4g%s%s" % (np.absolute(value), SUFFIX[p-4], UNITS[0 if x < 0 else 1])


def pishift(theta, r1, r2):
    x1, x2, x3 = teeshift(theta, 1/r1, 1/r2)
    return -1/x1, -1/x2, -1/x3


def teeshift(theta, r1, r2):
    theta = np.deg2rad(theta)
    zo = np.sqrt(np.abs(r1 * r2))
    x1 = np.sign(r1) * (zo - np.abs(r1) * np.cos(theta)) / np.sin(theta)
    x2 = np.sign(r1) * -zo / np.sin(theta)
    x3 = np.sign(r1) * (zo - np.abs(r2) * np.cos(theta)) / np.sin(theta)
    return x1, x2, x3


def watts(v):
    return np.abs(v[1])**2 * (v[0]/v[1]).real


def pinet(v, x1, x2, x3):
    v = multiply([[1, 0], [1 / (1j*x1), 1]], v)  # shunt
    v = multiply([[1, 1j*x2], [0, 1]], v)        # series
    v = multiply([[1, 0], [1 / (1j*x3), 1]], v)  # shunt
    return v


def teenet(v, x1, x2, x3):
    v = multiply([[1, 1j*x1], [0, 1]], v)        # series
    v = multiply([[1, 0], [1 / (1j*x2), 1]], v)  # shunt
    v = multiply([[1, 1j*x3], [0, 1]], v)        # series
    return v


def solve(ei, ii, data):
    n = len(ei)
    freq = data["frequency"]

    zi = ei / ii
    power = np.abs(ii**2) * zi.real
    feede = np.sqrt(data["power"] * data["feed"])
    ratio = np.sqrt(data["power"] / np.sum(power))
    ei *= ratio
    ii *= ratio
    power = np.abs(ii**2) * zi.real
    tie = data.get("tie", [])

    if tie:
        isum = np.sum([ ii[i-1] for i in data["tie"] ])
        for i in data["tie"]: ii[i-1] = isum
        zi = ei / ii
        power = np.abs(ii**2) * zi.real

    if data.get("divider1") or data.get("divider2") or data.get("divider2"):
        linez = [ np.sign(w) * data["feed"] for w in power ]
    else:
        linez = [ feede**2 / w for w in power ]

    match = [ np.concatenate([ lmatch(zi[i], linez[i]), lmatch(linez[i], zi[i]) ]) for i in range(n) ]
    combo = np.array([ [ i // (4 ** (n - k - 1)) % 4 for k in range(n) ] for i in range(4 ** n) ])

    print("! MHZ LINE               ZA        LMATCH                ZTUNE         ELINE        DPHASE", end="")
    print("              PI                          TEE              DPHASE   POWER           ZOUT")

    for d in combo:
        net = np.array([ match[i][k] for i, k in enumerate(d) ])
        if np.any(np.isnan(net.flatten())): continue

        print('!')
        for ref in range(n):

            line = np.array([ ei, ii ]).T
            pin = [ watts(v) for v in line ]
            for i, m, reverse in zip(range(n), net, d > 1):
                if reverse:
                    line[i] = multiply([[1, 1j*m[1]], [0, 1]], line[i])        # series
                    line[i] = multiply([[1, 0], [1 / (1j*m[0]), 1]], line[i])  # shunt
                else:
                    line[i] = multiply([[1, 0], [1 / (1j*m[0]), 1]], line[i])  # shunt
                    line[i] = multiply([[1, 1j*m[1]], [0, 1]], line[i])        # series
            zo = line[:,0] / line[:,1]

            ################

            for i, m, reverse in zip(range(n), net, d > 1):

                print('{:<7g} {:2d}'.format(freq, i + 1), end="")
                print(' {:16.5g}'.format(zi[i]), end="")
                # print(' {:7.3f}'.format(pin[i]), end="")

                if reverse:
                    print(' {:>8s} / {:>8s}'.format(component(m[1], freq), component(m[0], freq)), end="")
                else:
                    print(' {:>8s} \\ {:>8s}'.format(component(m[0], freq), component(m[1], freq)), end="")

                assert(np.abs(zo[i].imag) < 1e-3) 
                print(' {:14.2f}'.format(zo[i]), end="")
                print(' {:9.4f} {:8.3f}'.format(np.abs(line[i][0]), np.rad2deg(np.angle(line[i][0]))), end="")

                zfeed = feede**2 / power[i] if data.get("divider2") or data.get("divider3") else zo[i].real
                ref_theta = np.angle(line[ref][0])
                if data.get("divider2"): ref_theta -= np.pi / 2
                if data.get("divider3"): ref_theta += np.pi / 2
                theta = np.rad2deg(np.angle(line[i][0]) - ref_theta)
                theta = np.mod(theta + 180, 360) - 180
                print(' {:8.3f}'.format(theta), end="")

                # phase shift

                v = line[i]
                x1, x2, x3 = pishift(-theta, zo[i].real, zfeed)
                print(' {:>8s} {:>8s} {:>8s}'.format(component(x1, freq), component(x2, freq), component(x3, freq)), end="")
                if np.abs(theta) > 1e-3: v = pinet(v, x1, x2, x3)
                assert(np.abs((v[0]/v[1]).imag) < 1e-3) 
                assert(np.abs(np.mod(np.rad2deg(np.angle(v[0]) - ref_theta) + 180, 360) - 180) < 1e-3)

                v = line[i]
                x1, x2, x3 = teeshift(-theta, zo[i].real, zfeed)
                print(' | {:>8s} {:>8s} {:>8s}'.format(component(x1, freq), component(x2, freq), component(x3, freq)), end="")
                if np.abs(theta) > 1e-3: v = teenet(v, x1, x2, x3)
                assert(np.abs((v[0]/v[1]).imag) < 1e-3) 
                assert(np.abs(np.mod(np.rad2deg(np.angle(v[0]) - ref_theta) + 180, 360) - 180) < 1e-3)

                # results

                theta = np.rad2deg(np.angle(v[0]) - ref_theta)
                theta = np.mod(theta + 180, 360) - 180
                print(' {:8.3f}'.format(theta), end="")
                print(' {:7.3f}'.format(watts(v)), end="")
                print(' {:14.2f}'.format(v[0]/v[1]), end="")
                print()


if __name__ == "__main__":
    import sys
    np.seterr(divide='ignore', invalid='ignore')
    main(*sys.argv[1:])

